# Generated by Django 4.1.7 on 2023-03-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='technician_share',
            field=models.IntegerField(default=0),
        ),
    ]
