# Generated by Django 4.2 on 2023-04-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminhod',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
