# Generated by Django 4.1.7 on 2023-03-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='permanent_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
