# Generated by Django 4.1.7 on 2023-04-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Inprocess', 'Inprocess'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('Assign', 'Assign'), ('Proceed', 'Proceed')], default='New', max_length=20),
        ),
    ]
