# Generated by Django 4.1.7 on 2023-02-28 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician',
            name='user_id',
        ),
    ]
