# Generated by Django 4.1.7 on 2023-04-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0002_addon_quantity_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
