# Generated by Django 4.1.7 on 2023-03-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0002_remove_rebooking_task_rebooking_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='product',
        ),
        migrations.AddField(
            model_name='booking',
            name='products',
            field=models.ManyToManyField(related_name='bookings', to='homofix_app.product'),
        ),
    ]
