# Generated by Django 4.1.7 on 2023-03-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0002_support_permanent_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='d_o_b',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='support',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='support',
            name='marital_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
