# Generated by Django 4.1.7 on 2023-04-03 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0003_addon_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='homofix_app.booking'),
        ),
    ]
