# Generated by Django 4.1.7 on 2023-03-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0003_share_hod_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hodsharepercentage',
            name='percentage',
            field=models.IntegerField(),
        ),
    ]
