# Generated by Django 4.1.7 on 2023-02-28 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0003_technician_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician',
            name='user_id',
        ),
    ]
