# Generated by Django 4.1.7 on 2023-03-16 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0003_bookingproduct_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingproduct',
            name='price',
        ),
        migrations.RemoveField(
            model_name='bookingproduct',
            name='total_price',
        ),
    ]
