# Generated by Django 4.1.7 on 2023-03-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0003_support_d_o_b_support_father_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='application_form',
            field=models.FileField(blank=True, null=True, upload_to='Support/Application Form'),
        ),
    ]
