# Generated by Django 4.1.7 on 2023-04-03 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0004_alter_addon_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homofix_app.booking'),
        ),
    ]
