# Generated by Django 4.1.7 on 2023-03-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0004_alter_hodsharepercentage_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hodsharepercentage',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
