# Generated by Django 4.1.7 on 2023-03-23 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0004_alter_support_application_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician',
            name='category',
        ),
        migrations.AddField(
            model_name='technician',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homofix_app.subcategory'),
        ),
    ]
