# Generated by Django 4.1.7 on 2023-03-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0004_remove_bookingproduct_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingproduct',
            name='total_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
