# Generated by Django 4.1.7 on 2023-03-12 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0004_rename_products_booking_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homofix_app.customer'),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='product',
        ),
        migrations.AddField(
            model_name='booking',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homofix_app.product'),
            preserve_default=False,
        ),
    ]
