# Generated by Django 4.1.7 on 2023-02-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0004_remove_technician_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
