# Generated by Django 4.1.7 on 2023-04-03 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0005_alter_addon_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addon',
            name='addon_product',
        ),
        migrations.AddField(
            model_name='addon',
            name='addon_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homofix_app.addonsproduct'),
            preserve_default=False,
        ),
    ]
