# Generated by Django 4.1.6 on 2023-02-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0005_alter_product_product_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_pic',
            field=models.ImageField(upload_to='product_pic'),
        ),
    ]
