# Generated by Django 4.1.7 on 2023-03-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0005_alter_booking_customer_remove_booking_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='product',
        ),
        migrations.AddField(
            model_name='booking',
            name='products',
            field=models.ManyToManyField(related_name='bookings', to='homofix_app.product'),
        ),
    ]
