# Generated by Django 4.1.7 on 2023-02-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0005_technician_joining_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='application_form',
            field=models.ImageField(blank=True, null=True, upload_to='Application Form'),
        ),
    ]
