# Generated by Django 4.1.7 on 2023-03-29 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0006_customer_area_customer_city_customer_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
