# Generated by Django 4.1.7 on 2023-04-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0006_remove_addon_addon_product_addon_addon_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addon',
            name='addon_product',
        ),
        migrations.AddField(
            model_name='addon',
            name='addon_products',
            field=models.ManyToManyField(to='homofix_app.addonsproduct'),
        ),
    ]
