# Generated by Django 4.1.7 on 2023-02-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0006_technician_application_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='support_id',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
