# Generated by Django 4.1.7 on 2023-03-12 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0006_remove_booking_product_booking_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='products',
            new_name='product',
        ),
    ]
