# Generated by Django 4.2 on 2023-04-03 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0007_remove_addon_addon_product_addon_addon_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='addon_products',
            field=models.ManyToManyField(related_name='addons', to='homofix_app.addonsproduct'),
        ),
        migrations.CreateModel(
            name='TechnicianLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('technician', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='homofix_app.technician')),
            ],
        ),
    ]
