# Generated by Django 4.1.7 on 2023-03-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0007_rename_products_booking_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='product',
            field=models.ManyToManyField(to='homofix_app.product'),
        ),
    ]
