# Generated by Django 4.1.7 on 2023-02-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0007_support_support_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
