# Generated by Django 4.1.7 on 2023-03-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0007_customer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
