# Generated by Django 4.1.7 on 2023-03-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0007_remove_technician_category_technician_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='technician',
            name='subcategory',
            field=models.ManyToManyField(blank=True, null=True, to='homofix_app.subcategory'),
        ),
    ]
