# Generated by Django 4.2 on 2023-04-04 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0008_alter_addon_addon_products_technicianlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='spare_parts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='homofix_app.addonsproduct'),
        ),
    ]
