# Generated by Django 4.1.7 on 2023-03-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0008_remove_technician_subcategory_technician_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='document_form',
            field=models.FileField(blank=True, null=True, upload_to='Support/Document Form'),
        ),
    ]
