# Generated by Django 4.1.6 on 2023-02-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0008_alter_category_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='category',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
