# Generated by Django 4.1.7 on 2023-02-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0008_support_joining_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='application_form',
            field=models.ImageField(blank=True, null=True, upload_to='Support/Application Form'),
        ),
        migrations.AlterField(
            model_name='technician',
            name='application_form',
            field=models.ImageField(blank=True, null=True, upload_to='Expert/Application Form'),
        ),
    ]
