# Generated by Django 4.1.7 on 2023-03-25 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0009_support_document_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='technician',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homofix_app.subcategory'),
        ),
    ]
