# Generated by Django 4.2 on 2023-04-04 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0009_booking_spare_parts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='spare_parts',
        ),
    ]
