# Generated by Django 4.1.7 on 2023-02-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0009_support_application_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
