# Generated by Django 4.1.7 on 2023-03-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0009_remove_booking_product_booking_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='product',
        ),
        migrations.AddField(
            model_name='booking',
            name='products',
            field=models.ManyToManyField(to='homofix_app.product'),
        ),
    ]
