# Generated by Django 4.1.7 on 2023-02-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0010_product_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='order_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='order_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
