# Generated by Django 4.2 on 2023-04-04 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0010_remove_booking_spare_parts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddonsProduct',
            new_name='SpareParts',
        ),
    ]
