# Generated by Django 4.1.7 on 2023-03-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0010_remove_technician_subcategory_technician_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='technician',
            name='subcategories',
            field=models.ManyToManyField(blank=True, to='homofix_app.subcategory'),
        ),
    ]
