# Generated by Django 4.2 on 2023-04-04 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0011_rename_addonsproduct_spareparts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addon',
            name='booking',
        ),
        migrations.AddField(
            model_name='addon',
            name='booking_prod_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homofix_app.bookingproduct'),
            preserve_default=False,
        ),
    ]
