# Generated by Django 4.1.7 on 2023-03-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0011_remove_technician_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dis_amt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
