# Generated by Django 4.1.7 on 2023-03-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0011_rename_products_booking_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='product',
            field=models.ManyToManyField(related_name='bookings', to='homofix_app.product'),
        ),
    ]
