# Generated by Django 4.1.7 on 2023-03-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0012_product_dis_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='can_assign_task',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='support',
            name='can_cancel_booking',
            field=models.BooleanField(default=False),
        ),
    ]
