# Generated by Django 4.2 on 2023-04-04 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0012_remove_addon_booking_addon_booking_prod_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addon',
            name='addon_products',
        ),
        migrations.AddField(
            model_name='addon',
            name='addon_products',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homofix_app.spareparts'),
            preserve_default=False,
        ),
    ]
