# Generated by Django 4.2 on 2023-04-05 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0013_remove_addon_addon_products_addon_addon_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicianlocation',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='technicianlocation',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='technicianlocation',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='technicianlocation',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homofix_app.booking'),
        ),
        migrations.AddField(
            model_name='technicianlocation',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='technicianlocation',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='technicianlocation',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homofix_app.technician'),
        ),
    ]
