# Generated by Django 4.1.7 on 2023-03-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0013_support_can_assign_task_support_can_cancel_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='can_contact_us_enquiry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='support',
            name='can_expert_create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='support',
            name='can_new_booking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='support',
            name='can_rebooking',
            field=models.BooleanField(default=False),
        ),
    ]
