# Generated by Django 4.1.6 on 2023-02-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0016_technician_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician',
            name='id_number',
        ),
        migrations.AddField(
            model_name='technician',
            name='id_proof_document',
            field=models.ImageField(blank=True, null=True, upload_to='ID Proof'),
        ),
    ]
