# Generated by Django 4.1.7 on 2023-03-04 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0018_booking_city_alter_booking_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technician',
            old_name='expert_in',
            new_name='rating',
        ),
    ]
