# Generated by Django 4.1.7 on 2023-03-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0019_rename_expert_in_technician_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
