# Generated by Django 4.1.7 on 2023-02-16 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0020_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
