# Generated by Django 4.1.7 on 2023-03-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0020_booking_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Deactivate', 'Deactivate'), ('Hold', 'Hold')], default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='technician',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Deactivate', 'Deactivate'), ('Hold', 'Hold')], default='Active', max_length=50),
        ),
    ]
