# Generated by Django 4.1.7 on 2023-02-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0022_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
