# Generated by Django 4.1.7 on 2023-03-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0022_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='status_choice',
            field=models.CharField(choices=[('New', 'New'), ('in_process', 'In Process'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('Assign', 'Assign')], default='New', max_length=50),
        ),
    ]
