# Generated by Django 4.1.7 on 2023-02-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0023_product_warranty'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
