# Generated by Django 4.1.7 on 2023-02-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0024_product_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
