# Generated by Django 4.1.7 on 2023-03-07 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0026_alter_technician_status_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status_choice',
            field=models.CharField(choices=[('New', 'New'), ('in_process', 'In Process'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('Assign', 'Assign')], default='New', max_length=50),
        ),
    ]
