# Generated by Django 4.1.7 on 2023-03-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0028_alter_task_status_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status_choice',
            field=models.CharField(choices=[('in_process', 'In Process'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('Assign', 'Assign')], default='in_process', max_length=50),
        ),
    ]
