# Generated by Django 4.1.7 on 2023-02-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0029_alter_customuser_user_type_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deactivate', 'Deactivate'), ('Hold', 'Hold')], default='Active', max_length=50),
        ),
    ]
