# Generated by Django 4.1.7 on 2023-03-07 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0029_alter_task_status_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status_choice',
        ),
    ]
