# Generated by Django 4.1.7 on 2023-03-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0030_remove_task_status_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician',
            name='status_choice',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Inprocess', 'Inprocess'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('Assign', 'Assign')], default='New', max_length=20),
        ),
    ]
