# Generated by Django 4.1.7 on 2023-02-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0030_support_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='Support'),
        ),
    ]
