# Generated by Django 4.1.7 on 2023-03-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0031_remove_technician_status_choice_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Inprocess', 'Inprocess'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('Assign', 'Assign')], default='Assign', max_length=20),
        ),
    ]
