# Generated by Django 4.1.7 on 2023-02-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0035_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'HOD'), ('2', 'Technician'), ('3', 'Support'), ('4', 'Customer')], default='1', max_length=10),
        ),
    ]
