# Generated by Django 4.1.7 on 2023-02-21 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0036_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_Date',
            new_name='booking_date',
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='homofix_app.customer'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='homofix_app.product'),
        ),
    ]
