# Generated by Django 4.1.7 on 2023-02-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0040_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('in_process', 'In Process'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='New', max_length=20),
        ),
    ]
