# Generated by Django 4.1.7 on 2023-02-27 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0041_alter_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
    ]
